### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by coney4** [opentibiabr/OTServBR-Global#198]
I dont know after which action this happend but it is on my server console several times

Lua Script Error: [CreatureScript Interface]
data/creaturescripts/scripts/fly.lua:onModalWindow
data/creaturescripts/scripts/fly.lua:3: attempt to index field 'Exaust' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/creaturescripts/scripts/fly.lua:3: in function <data/creaturescripts/scripts/fly.lua:1>

**Comment by eduardodantas95** [comment]
This is fixed on the pull #193

**Comment by coney4** [comment]
but fly.lua still exists and it is registred in login.lua ( player:registerEvent("fly") )

**Comment by eduardodantas95** [comment]
Fixed, thanks for your report.
